config/routes.rb
Rails.application.routes.draw do

  root 'cars#index'

  get 'login' => 'sessions#login'    # if different than get 'login':   , as: 'something else'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :cars

  resources :users, only: [:new, :create],
            path_names: { new: 'signup' }

end

app/models/car.rb
# documentation
class Car < ActiveRecord::Base
  validates :make, :model, :year, :price, presence: true
  validates :price,
            numericality: {
              greater_than: 0.00,
              less_than: 1_000_000
            }
  validates :year, inclusion: 1769..Time.zone.now.year
end

app/models/student.rb
class Student < ActiveRecord::Base
  scope :males, -> { where(sex: 'M') }
  scope :females, -> { where(sex: 'F') }
  scope :teens, -> { where(date_of_birth: 18.years.ago..13.years.ago)}
  def seed_custom
      Student.create(
        :date_of_birth => "2014-08-19",
        :eye_color => "green",
        :first_name => "Vicky",
        :middle_name => "M",
        :last_name => "Smith",
        :hair_color => "brown",
        :height => 62,
        :sex => "F",
        :weight => 150
      )

      Student.create(
      :date_of_birth => "2014-08-20",
      :eye_color => "blue",
      :first_name => "Tammi",
      :middle_name => "S",
      :last_name => "Love",
      :hair_color => "blond",
      :height => 69,
      :sex => "F",
      :weight => 140
      )

      Student.create(
      :date_of_birth => "2014-08-21",
      :eye_color => "blue",
      :first_name => "Jessee",
      :middle_name => "S",
      :last_name => "Ford",
      :hair_color => "blond",
      :height => 69,
      :sex => "F",
      :weight => 140
      )
  end



  def self.seed_data!
    ages = (5..18).to_a
    heights = {
      5  => (40..46).to_a,
      6  => (42..49).to_a,
      7  => (44..52).to_a,
      8  => (47..54).to_a,
      9  => (49..57).to_a,
      10 => (50..59).to_a,
      11 => (52..61).to_a,
      12 => (54..64).to_a,
      13 => (56..66).to_a,
      14 => (59..70).to_a,
      15 => (62..72).to_a,
      16 => (63..73).to_a,
      17 => (64..74).to_a,
      18 => (65..75).to_a,
    }
    500.times do |number|
      age = ages.sample
      date_of_birth = (age).years.ago + rand(11).months + rand(30).days
      height = heights[age].sample
      Student.create(
        :first_name => Faker::Name.first_name,
        :middle_name => Faker::Name.first_name,
        :last_name => Faker::Name.last_name,
        :date_of_birth => date_of_birth,
        :hair_color => ['red', 'brown', 'black', 'blonde'].sample,
        :eye_color => ['blue', 'green', 'brown'].sample,
        :height => height,
        :weight => random_weight_for_height(height),
        :sex => ['M', 'F'].sample
      )
    end
  end

  private

  def self.random_weight_for_height(height)
    bmi = (19..40).to_a.sample
    sprintf("%.2f", ((height * height) * bmi)/703)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, :last_name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/cars_controller.rb
# documentation
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    creation_message ="#{@car.year} #{@car.make} #{@car.model} created"
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: creation_message }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  # strong params allows white listing
  def car_params
    params.require(:car).permit(:make, :model, :year, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:id] = user.id
      redirect_to root_path,
        notice: "Welcome back #{user.first_name.capitalize}"
    else
      flash[:error] =  "Invalid email or password"
      render :login
    end
  end

  def destroy
    if user = current_user
      session.delete(:id)
      redirect_to root_path, notice: "#{user.email} has been logged out."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    render :login
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to root_path,
        notice: "Thank you for signing up #{@user.first_name.capitalize}"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email,
      :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Cars</h1>
<table class='table'>
  <th>Make</th>
  <th>Model</th>
  <th>Year</th>
  <th>Price</th>
  <% @cars.each do |car| %>
  <tr>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= car.year %></td>
    <!--<td><%= sprintf(‘%.2f’, car.price) %></td>-->
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>

  </tr>
<% end %>
</table>
</br>
</br>

<%= link_to 'New Car', new_car_path %>
<%= link_to 'login', login_path %>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'form' %>

app/views/cars/show.html.erb
<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/_authentication.html.erb
<% if current_user %>
  Signed in as <%= current_user.email %>
  <%= link_to 'Logout', logout_path, method: :delete %>

<% else %>
  <%= link_to 'Signup', new_user_path %>
  <%= link_to 'Login', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>

<% end %>
<%= render 'layouts/authentication' %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>


  <%= f.submit 'Signup' %>
<% end %>